opendistro/for-elasticsearch-docs

docs/install/docker-security.md
docs/install/docker.md
docs/install/encryption-at-rest.md
docs/security/api.md
docs/security/index.md
docs/security/saml.md

Demonstrates certificate overrides

---

README.md

*Issue #, if available:* N/A
When following the instructions from inside a ruby:latest container:
```
root@ad8bfa6165b9:/data# bundle exec jekyll serve
Configuration file: /data/_config.yml
Source: /data
Destination: /data/_site
Incremental build: disabled. Enable with --incremental
Generating...
done in 8.085 seconds.
Auto-regeneration: enabled for '/data'
Server address: http://127.0.0.1:4000/for-elasticsearch-docs/
Server running... press ctrl-c to stop.
```
Attempting to access / results in a HTTP 404.

README: Fix link to locally-served documentation.

---

docs/elasticsearch/full-text.md
docs/install/docker.md

Reproduced the simple match query in a curl command to hopefully give new users a better understanding of how to interact with opendistro elasticsearch. 

Curl example for simple match query

---

docs/security/document-level-security.md

*Issue #, if available:* N/A
I beat my head against a wall for a bit trying to figure out how to get attribute-level security working.  I ended up having to read through source-code to figure out how to substitute user attributes into the `_dls_` rule.
I wrote some documentation to avoid having to re-discover this again at some later date.

Add introduction to the mechanics of document level security.

---

docs/install/deb.md

Modified Debian packages installation steps. This is necessary because previously we had elasticsearch-oss in our repo, which we are now taking out.

changed deb installation steps

---

docs/security/impersonation.md

*Issue #, if available:* N/A
*Description of changes:* I found references to user impersonation in the default config file, but had to dive into the source code to figure out what request header to set to make it work.
Afterwards, I wrote up some a quick introduction that will hopefully save other people from having to go spelunking.

Add intro to user impersonation

---

docs/security-configuration/saml.md

Add documentation for SAML service provider signature configuration. See https://github.com/opendistro-for-elasticsearch/security-advanced-modules/blob/master/src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java#L203

Add saml sp cert filepath config options

---

docs/security-access-control/api.md

In this PR I fixed a small typo.
Old examples with `backendroles` produced the following error:
```json
{"status":"error","reason":"Invalid configuration","invalid_keys":{"keys":"backendroles"}}
```

Rename backendroles to backend_roles in rolesmapping API docs

---

docs/security-access-control/multi-tenancy.md

The current elasticsearch `config.yml` has slightly updated configs, see: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml
- main yaml key is now `config`
- `do_not_fail_on_forbidden` is not anymore under `kibana`

Fix wrong yaml examples

---

docs/sql/endpoints.md
docs/sql/monitoring.md
docs/sql/protocol.md
docs/sql/settings.md

*Description of changes:* Adding 4 new documents for basic usage of SQL plugin which are generated from template and test code in issue https://github.com/opendistro-for-elasticsearch/sql/issues/293.

SQL plugin docs for basic usage

---

docs/security-audit-logs/index.md

It was selected **true** when the purpose is to disable it.

Disable 'opendistro_security.audit.enable_rest'.

---

docs/ism/policies.md

Parameter **min_age** is invalid, it must be **min_index_age**.
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/policies/#rollover

Fix rollover condition.

---

docs/elasticsearch/configuration.md

"This setting is deprecated in 7.x and will be removed in version 8.0."
It seems that it's not recommended to permit more than 1 node to access to directory data on production clusters.
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#max-local-storage-nodes

Remove 'node.max_local_storage_nodes'.

---

docs/install/plugins.md
docs/knn/index.md

KNN update for 1.6.0

---

docs/elasticsearch/snapshot-restore.md

With default doc options Elasticsearch does not start. For example editing "endpoint" parameter Elasticsearch gives this error:
```
[2020-04-18T11:45:54,211][ERROR][o.e.b.Bootstrap          ] [elasticsearch-node] Exception
java.lang.IllegalArgumentException: unknown setting [endpoint] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:532) ~[elasticsearch-7.6.1.jar:7.6.1]
at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:477) ~[elasticsearch-7.6.1.jar:7.6.1]
at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:448) …
```

Full definition of S3 client settings.

---

docs/security-access-control/api.md

In the API doc, changed the sample response of the get request for an action group :
It was previously documented like this:
```json
{
"SEARCH" : [ "indices:data/read/search*", "indices:data/read/msearch*", "SUGGEST" ]
}
```
which I think is false, example request on this endpoint
$ curl https://localhost:9200/_opendistro/_security/api/actiongroups/custom_action_group?pretty
{
"custom_action_group": {
"reserved": false,
"hidden": false,
"allowed_actions": [
"kibana_all_read",
"indices:admin/aliases/get",
"indices:admin/aliases/exists"
],
"static": false
}
}
As a result, I have changed the corresponding section to this :
```json
{
"read": {
"reserved": true,
"hidden": false,
"allowed_actions": [
"indices:data/read*",
"indices:admin/mappings/fields/get*"
],
"type": "index",
"description": …
```

Fixed the API doc for the GET actiongroups endpoint.

---

docs/install/helm.md

tiller is deprecated in version 3 and also the install command is changed

---

docs/security/configuration/ldap.md

*Issue #:* https://github.com/opendistro-for-elasticsearch/security/issues/211
*Description of changes:* From the hidden configuration settings for LDAP authentication, the timeout settings should be made visible.
A recent run-in with an AD server that makes use of 2FA required a deep dive into the codebase.  The timeout settings were found, tested and works as expected, resulting in an acceptable timeframe to complete an AD login backed by a 2FA process.
The connection timeout affects the amount of time that is allowed to complete the 2FA process (at least in my case).  It's suggested to leave the response timeout at the default of 0 and adjust the connection timeout according to needs.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Add LDAP Timeout Settings to Documentation

---

docs/install/helm.md

https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/251
This PR is to update helm commands with correct hyphan syntax

Update helm commands with correct hyphan syntax

---

docs/upgrade/1-10-1.md

https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/418
Add ODFE Kibana 1.10.1 upgrade instructions to ODFE docs for breaking changes on cookies security settings

Add ODFE Kibana 1.10.1 upgrade instructions to ODFE docs for breaking changes on cookies security settings

---

docs/security/configuration/saml.md

*Issue #, if available: See https://github.com/opendistro-for-elasticsearch/security/pull/539
SAML config now supports encrypted assertions. Updating docs to reflect that.

Expand on sp.signature_private_key configuration usage

---

docs/knn/index.md
docs/knn/settings.md

KNN custom scoring

---

docs/ad/index.md
docs/kibana/plugins.md

High cardinality

---

docs/security/configuration/security-admin.md

Add backslash to fix multi-line command

Fix Multi-Line SecurityAdmin Command Usage Example

---

docs/security/configuration/ldap.md

Learned about the undocumented parameter `max_nested_depth` for LDAP authorization configuration from opendistro-for-elasticsearch/security#887
This PR documents this parameter.

Document max_nested_depth in LDAP authz config

---

docs/kibana/plugins.md

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/254
*Description of changes:* The endpoint is `kibana-plugins`, not `kibana-plugin`.

Fix typo in kibana-reports url endpoint

---

docs/knn/index.md

In this PR, I refactor the documentation about k-NN to include more information about custom scoring. Additionally, I update the custom scoring parameter from `vector` to `query_value`, which was changed in https://github.com/opendistro-for-elasticsearch/k-NN/pull/267.

Add more details about custom scoring for k-NN

---

docs/security/configuration/disable.md

From kibana 7.10.0, the security plugin name is changed, so I fixed commands to successfully remove it.

fix commands to remove security plugin for kibana

---

docs/knn/approximate-knn.md
docs/knn/knn-score-script.md
docs/knn/painless-functions.md

This change adds the L1 space to the documentation. This feature was added in this PR: https://github.com/opendistro-for-elasticsearch/k-NN/pull/310

Add L1Norm to k-NN docs

---

docs/security/configuration/client-auth.md

A client is just anything that connects to the cluster, so terms like "client-based" could apply to anything. We're specifically addressing authentication through client certificates.

Wording tweaks for client certificate authentication

---

docs/alerting/api.md

Issue #417 
Added new Get Alerts API and tweaked Acknowledge Alerts to recommend Get Alerts API instead of querying `.opendistro-alerts`

Alerting api

---

_sass/custom/custom.scss

Default style from just-the-docs theme has a quite large line-height for code sections, and the font-family list only take macOS and Windows into consideration. On Linux ( RHEL 7 in my case ), Droid Sans Mono looks better.

improve code section look

---

docs/knn/knn-score-script.md

Add separate example for k-NN hamming distance

Add separate hamming distance example

---

docs/alerting/monitors.md

Issue #390 
Added some `ctx` variables to the alerting plugins available variables table 

Added some variables to alerting variables table

---

docs/alerting/monitors.md

Issue #481 
Updated definitions in Key Terms table

Edited key terms table with new definitions

---

docs/sql/settings.md

Adding missing settings per https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst

Add missing sql settings

---

_config.yml
version-history.md

Update version to 1.13.3

---

docs/install/docker.md

https://github.com/opendistro/for-elasticsearch-docs/issues/511
Change Kibana Docker version to "latest" since we didn't publish a 1.13.3 version. Kibana didn't change because 1.13.3 only fixes the log4j stuff in the ES distribution, Kibana is written in Javascript so it isn't affected. See https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/793
@keithhc2 not sure if you prefer to put 1.13.2 here instead of latest, or whether you want to add any explanatory text around the version mismatch. Feel free to do either.

Update Kibana Docker version

---

docs/cli/index.md
docs/other/index.md
docs/pa/index.md
docs/pa/reference.md
docs/previousversions/index.md
docs/troubleshoot/index.md
docs/troubleshoot/openid-connect.md
docs/troubleshoot/saml.md
docs/troubleshoot/tls.md

Product is being renamed to remove "Elasticsearch"

Rename ODFE --> Open Distro

---

docs/im/ism/policies.md

In our current documentation we don't specifically say that if an index is in read_only mode, it will not refresh.

Clarify ISM refresh behavior
