opendistro/for-elasticsearch-docs

- docs/security/concepts.md
Minor documentation typo: TSL -> TLS
> Fix typo TSL to TLS

- docs/security/openid-connect.md
> kibana: Document openid.base_redirect_url

- docs/install/docker-security.md
- docs/install/docker.md
- docs/kibana/index.md
- docs/security/disable.md
- index.md
> Preparing for 0.7.1

- docs/alerting/cron.md
> Adds information of custom cron expressions

- docs/elasticsearch/snapshot-restore.md
> Snapshot and restore documentation

- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/kibana/index.md
- docs/security/disable.md
- index.md
> Preparing for 0.8.0

- docs/install/deb.md
- docs/kibana/index.md
> Debian install

- docs/install/plugins.md
> Adds standalone plugin install from ZIP files

- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/kibana/index.md
- docs/pa/reference.md
- docs/security/disable.md
- index.md
> Preparing for 0.9.0

- docs/install/other-components.md
- docs/install/plugins.md
- docs/kibana/maptiles.md
- docs/kibana/plugins.md
- docs/security/disable.md
- docs/sql/jdbc.md
- docs/troubleshoot/index.md
- Clarifies troubleshooting step
- Adds "Other Components" list
- Minor tweaks
> Adds content on Kibana plugins

- docs/pa/api.md
> Shorten sample return, adds brief explanation

- docs/install/docker-security.md
- docs/install/docker.md
- docs/security/cross-cluster-search.md
- docs/security/default-action-groups.md
- docs/security/disable.md
- docs/security/document-level-security.md
- docs/security/generate-certificates.md
- docs/security/ldap.md
- docs/security/openid-connect.md
- docs/security/permissions.md
- docs/security/saml.md
- docs/security/security-admin.md
- docs/security/tls-configuration.md
> Adds content on generating your own certificates

- docs/alerting/api.md
- docs/alerting/monitors.md
> Custom webhook improvements

- .gitignore
- build.sh
- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/1-0-0.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
> Preparing for 1.0.1

- docs/alerting/settings.md
https://github.com/opendistro/for-elasticsearch-docs/issues/102
> Update alert settings

- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/index.md
- docs/install/plugins.md
- docs/kibana/index.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/index.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.0.2

- docs/elasticsearch/snapshot-restore.md
- docs/install/deb.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/api.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.1.0

- docs/install/deb.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- version-history.md
> Preparing for 0.10.0

- docs/security-configuration/index.md
The page title should match the table of contents. 
> Change page title to match table of contents.

- _sass/custom/custom.scss
- docs/install/plugins.md
- docs/install/rpm.md
> PA improvements

- docs/elasticsearch/catapis.md
- docs/elasticsearch/full-text.md
- docs/elasticsearch/snapshot-restore.md
> added info about CAT APIs

- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/api.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/security-configuration/tls.md
- docs/upgrade/1-0-0.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.2.0

- docs/security-configuration/openid-connect.md
Fix link to Keycloak documentation
> Fix link to Keycloak documentation

- docs/security-configuration/openid-connect.md
> TSL to TLS

- docs/elasticsearch/logs.md
- docs/elasticsearch/snapshot-restore.md
> Log configuration content

- docs/security-configuration/ldap.md
Update to reflect configuration changes made in the com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7 class in the security plugin.
> Update LDAP configuration documentation

- docs/install/plugins.md
> Anomaly Detection Changes

- docs/elasticsearch/reindex-data.md
> Incorporated feedback for the Reindex section 

- README.md
- docs/elasticsearch/snapshot-restore.md
- docs/install/deb.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/install/tar.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.2.1

- docs/elasticsearch/snapshot-restore.md
- docs/im/api.md
- docs/im/index.md
- docs/im/managedindices.md
- docs/im/policies.md
- docs/im/settings.md
- docs/install/deb.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/install/tar.md
- docs/ism/settings.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.3.0

- docs/install/docker-security.md
- docs/install/windows.md
- docs/kibana/index.md
- docs/troubleshoot/index.md
> Minimal Windows docs

- docs/rca/index.md
@ditac I took a stab at a very high-level summary of how one interacts with the plugin and what it does, but let me know if I missed the mark. I probably did. :grinning:
> Brief summary of the RCA plugin

- docs/im/api.md
- docs/im/policies.md
> fixed json and added ctx variable types

- docs/ism/api.md
> fixed ism json errors

- docs/security-configuration/proxy.md
> Adding content on proxy-based auth

- docs/elasticsearch/index-alias.md
- docs/elasticsearch/reindex-data.md
- docs/install/helm.md
> Index alias update

- docs/install/helm.md
> Helm updates

- docs/elasticsearch/catapis.md
- docs/elasticsearch/index-templates.md
- docs/elasticsearch/reindex-data.md
> Adding index template section

- docs/security-access-control/field-masking.md
> Remove extra chars.

- docs/elasticsearch/search-template.md
> Added a search templates section

- docs/other/index.md
> Ansible role to deploy opendistroelasticsearch

- docs/elasticsearch/bool.md
> Boolean queries

- docs/elasticsearch/cluster.md
> Cluster updates

- docs/elasticsearch/bool.md
> filter update

- docs/ism/index.md
- docs/ism/policies.md
> ism close and replica_count updates

- docs/ism/policies.md
> fixed rollover alias

- docs/elasticsearch/term.md
> added term-level queries

- docs/security-access-control/users-roles.md
> added steps for read_only and bulk access roles

- docs/elasticsearch/term.md
> fixed minor formatting

- docs/ism/index.md
> changed ism security note

- docs/ism/policies.md
> fixed force merge description

- docs/elasticsearch/index-data.md
> added read, update, and delete operations

- docs/security-access-control/users-roles.md
> sample roles edits

- version-history.md
> added release highlights

- docs/install/plugins.md
> Job scheduler plugin

- docs/troubleshoot/index.md
> Fix the step number

- docs/elasticsearch/cluster.md
*Issue #, if available: #219 
Add h in https
> Fix broken Rally link

- docs/ism/policies.md
To match some index like "logs-000001".
> Fix regexp.

- docs/install/ami.md
> Adds AMI section

- docs/elasticsearch/full-text.md
- docs/elasticsearch/snapshot-restore.md
- docs/install/docker-security.md
- docs/install/docker.md
- docs/install/helm.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/install/tar.md
- docs/install/windows.md
- docs/ism/index.md
- docs/kibana/index.md
- docs/kibana/plugins.md
- docs/security-access-control/cross-cluster-search.md
- docs/security-configuration/disable.md
- docs/upgrade/cluster-restart.md
- docs/upgrade/rolling.md
- index.md
- version-history.md
> Preparing for 1.7.0

- docs/ad/api.md
> updated AD apis

- docs/ad/api.md
- docs/ad/index.md
> minor changes to detector interval

- docs/ad/index.md
> incorporated AD feedback

- docs/sql/basic.md
> SQL limit fix

- docs/install/plugins.md
> install steps for AD

- docs/install/tar.md
Document instructions for running Performance Analyzer on a tarball
> Document instructions for running Performance Analyzer on a tarball

- docs/ad/index.md
> added count aggregation

- docs/ism/policies.md
> added ism snapshot option

- docs/knn/index.md
- docs/knn/settings.md
Updated k-NN documentation to include information about cosine similarity.
> Knn update 1.8

- docs/ad/index.md
> added cpu note

- docs/elasticsearch/term.md
> added edits

- docs/ism/policies.md
> added error notification

- docs/elasticsearch/cluster.md
> allocation not yet supported in ism

- docs/ism/policies.md
> rollover changes

- docs/ism/policies.md
> fixed links

- docs/ism/policies.md
> changed error_notification level

- docs/install/helm.md
Update helm installation to let users know how to choose the specific ODFE version
> Update helm installation to let users know how to choose the specific ODFE version

- docs/install/deb.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/install/tar.md
- docs/pa/index.md
- docs/rca/api.md
- docs/rca/index.md
- docs/rca/reference.md
*Issue #, if available:* N/A
*Description of changes:* Added updated documentation for PA 1.9.0 release
> Basic changes for PA 1.9.0

- docs/ism/policies.md
> added index priority support for ISM

- docs/ism/policies.md
> fixed link

- docs/kibana/plugins.md
> update ism kibana version

- docs/sql/odbc.md
> pointing to readme for most up-to-date info

- docs/sql/odbc.md
> SQL ODBC - Added Tableau and Excel links

- docs/sql/odbc.md
> fixed Tableau link

- docs/elasticsearch/index-templates.md
- docs/ism/index.md
- docs/ism/settings.md
> Added template example and replaced _template with _index_template

- docs/ism/policies.md
@dbbaughe I might have destroyed some of your nuance, but let me know what you think.
> Add cron transition example

- docs/install/deb.md
> [deb] improve notes on Debian

- docs/install/docker-security.md
- docs/security/configuration/openid-connect.md
- docs/security/configuration/security-admin.md
Some little rewording to make some things a bit more clear in the docs.
> Make some things a little bit clearer

- docs/sql/functions.md
> added sub categories and aggregate functions

- docs/elasticsearch/cluster.md
- docs/ism/policies.md
> added allocation operation to ISM

- docs/ism/refresh-analyzer.md
> Refresh analyzers update

- docs/alerting/monitors.md
> Alerting email-final updates

- docs/elasticsearch/index-templates.md
> index_template sample is broken

- docs/security/access-control/document-level-security.md
- docs/security/access-control/multi-tenancy.md
- docs/security/configuration/proxy.md
> Update docs for proxy configuration

- docs/sql/functions.md
> updated sql functions

- docs/ad/index.md
> added sample detectors

- docs/ad/cli.md
> added ad cli info

- docs/ad/index.md
> high cardinality formula update

- docs/notebooks/index.md
> updated notebook intro

- docs/ad/index.md
> updated high cardinality formula note

- docs/sql/datatypes.md
> SQL data types

- docs/ppl/index.md
> changed abbreviation

- docs/ppl/commands.md
- docs/ppl/endpoint.md
- docs/ppl/functions.md
- docs/ppl/protocol.md
- docs/ppl/settings.md
> fixed name error

- docs/ppl/commands.md
- docs/ppl/endpoint.md
- docs/ppl/functions.md
- docs/ppl/protocol.md
- docs/ppl/settings.md
> Ppl name fix

- docs/knn/index.md
update to knn_score instead of knn_store
> [k-NN] Fix typo

- docs/ad/security-ad.md
- docs/ad/security.md
- docs/upgrade/1-11.0.md
> Security for anomaly detection

- docs/ad/api.md
- docs/ad/settings.md
> High cardinality updates

- docs/knn/index.md
Added formulas for how to calculate Euclidian distance and cosine similarity, as well as scoring conversions for approximate k-NN and custom scoring
> Updated KNN calculations with formulas

- docs/ism/index-rollups.md
> added rollup example

- docs/ism/api.md
The change policy docs in ISM are a bit unclear and don't give enough information on what actually happens.
This tries to break down the process a bit more so the user knows what will happen after using the API.
> Updates ISM change policy API docs

- docs/ism/settings.md
The template element was missing from the example _index_template
> Fix ISM settings template

- docs/ism/index-rollups.md
> added aggregation to query

- docs/elasticsearch/index-templates.md
> Added note to indicate change in template API

- docs/trace/data-prepper-reference.md
> IAM signing for Trace Analytics

- docs/async/index.md
- docs/async/security.md
- docs/async/settings.md
- docs/security/access-control/permissions.md
- docs/security/access-control/users-roles.md
> Asynchronous search

- docs/install/deb.md
- docs/install/rpm.md
- docs/install/tar.md
Add the x64 and arm64 instructions for deb ES-oss install
> Add the x64 and arm64 instructions for deb ES-oss install

- docs/install/helm.md
- docs/install/windows.md
- docs/kibana/index.md
Modify the Kibana windows download links in the install doc. Also change the attributes in the curl to validate the install in windows. Modify the typo in helm docs. 
> Modify the Kibana windows download links in the install doc

- docs/kibana/index.md
Add x64 and ARM64 Kibana install steps.
> Add x64 and ARM64 Kibana install steps.

- docs/knn/approximate-knn.md
This change updates our description of the cosine similarity scoring in approximate k-NN.
Related issue: https://github.com/opendistro-for-elasticsearch/k-NN/issues/325
> Fix cosine similarity definition

- docs/im/index-rollups/index.md
- docs/im/index-rollups/rollup-api.md
- docs/im/index.md
- docs/im/ism/api.md
- docs/im/ism/index.md
- docs/im/ism/managedindices.md
- docs/im/ism/policies.md
- docs/im/ism/settings.md
- docs/im/refresh-analyzer/index.md
> Index management reorg

- docs/install/deb.md
- docs/install/docker.md
- docs/install/plugins.md
- docs/install/rpm.md
- docs/install/tar.md
#428
Update performance analyzer plugin documentation to match instructions for current release.
> Update Performance Analyzer plugin instructions.

- docs/elasticsearch/tasksapis.md
Continuation off of a closed PR
Issue #394 - created documentation on the _tasks API and edited based on prior comments 
> Created tasks API documentation and made some tweaks based on comments

- docs/previousversions/index.md
Added a new page in docs to view previous versions of Open Distro for Elasticsearch bundled artifacts 
> Adding 'previous version' page to Open Distro for Elasticsearch docs

- docs/security/configuration/client-auth.md
- docs/security/configuration/generate-certificates.md
Issue: #254 
Added some instructions on how to configure `yml` files to accept client certificates.
> Added instructions on how to authenticate using client certificates

- docs/elasticsearch/snapshot-restore.md
- docs/security/configuration/generate-certificates.md
*Issue #, if available: N/A
*Description of changes: Just getting my feet wet editing ODFE docs
> Minor edits to snapshot docs

- docs/im/ism/policies.md
Some of the relative URLs needed an extra `../` to be correct
> Fix relative URLs

- docs/knn/settings.md
This value should be 50% not 60%
> Fix default circuit breaker limit for knn

- docs/im/ism/policies.md
> Ism template policy

- docs/security/access-control/api.md
- docs/security/access-control/users-roles.md
- docs/security/configuration/yaml.md
Issue: #226 
Added some instructions on how to map opendistro_security_roles in user creation and user updates
> Updated to include instructions on how to map opendistro_security_roles

- docs/ad/index.md
> Impact of features on the accuracy of an AD model

- docs/cli/index.md
> odfe-cli syntax changes, adds KNN

- docs/trace/data-prepper-reference.md
- docs/trace/data-prepper.md
- docs/trace/get-started.md
**Note**: To be merged on 03/25 to match new Data Prepper version release date.
* Updating Data Prepper documentation to match changes coming in the 03/25 beta release.
* Renamed "processor" to "prepper"
* Added new Peer Forwarder plugin
* Added new, required server config file
* Renamed "master" branch to "main" (updated links)
> Updated trace analytics documentation to match recent changes.

- docs/security/configuration/client-auth.md
Added Beats settings for client cert authentication
> Added configuration for Beats

- docs/trace/data-prepper.md
* Found an invalid configuration file in the Data Prepper docs. Minor fix.
> Fixing invalid example config in Data Prepper docs.

- README.md
- _config.yml
- docs/install/plugins.md
- docs/kibana/plugins.md
- docs/trace/index.md
- version-history.md
> Updates for 1.13.2

- docs/alerting/api.md
- docs/alerting/monitors.md
Issue #452 
Added timezone to creating a monitor 
> Tweaked language to include timezone instructions

- docs/install/docker.md
> Docker Performance Analyzer directory naming

- docs/im/ism/policies.md
> Fix numbered list

- docs/im/ism/policies.md
> Fix for real this time

- docs/sql/endpoints.md
> minor fixes

- docs/install/docker-security.md
- docs/install/docker.md
- docs/security/configuration/client-auth.md
- docs/security/configuration/generate-certificates.md
Issue #470 
Added some information on how to configure Docker to use user-created certificates
> Added information on how to use certificates with Docker configuration

- docs/security/configuration/tls.md
> fix for trustore issue

- docs/im/ism/api.md
> ism warning

- docs/security/configuration/client-auth.md
- docs/security/configuration/ldap.md
- docs/security/configuration/saml.md
- docs/upgrade/1-11-0.md
> Remaining "ODFE"s

- NOTICE
- README.md
- _config.yml
> Few more minor changes

- docs/im/ism/policies.md
Adjusted `min_size` definition
> Tweaked `min_size` definition

- _layouts/default.html
Signed-off-by: Miki <miki@amazon.com>
> EOL Open Distro
